# Generated by Django 5.0.3 on 2024-10-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='picture',
        ),
    ]
