# Generated by Django 5.0.3 on 2024-10-01 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_basicinfo_email_remove_basicinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillmodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skillmodel',
            name='user',
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50, null=True)),
                ('job_description', models.TextField(max_length=500, null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='media/cv')),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('job_location', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=50, null=True)),
                ('deadline', models.DateField(null=True)),
                ('qualifications', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EducationModel',
        ),
        migrations.DeleteModel(
            name='SkillModel',
        ),
    ]
