# Generated by Django 5.1.1 on 2024-10-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_skillmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='company_website',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='linkedin',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='permanent_address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='present_address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
