# Generated by Django 5.1.1 on 2024-10-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_basicinfo_company_website_basicinfo_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyNowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=50, null=True)),
                ('applicant_email', models.EmailField(max_length=100, null=True)),
                ('applicant_cv', models.FileField(null=True, upload_to='cv/')),
                ('applicant_cover_letter', models.TextField(null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.jobmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
