# Generated by Django 5.1.1 on 2024-10-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_degreemodel_fieldofstudymodel_intermediateskillmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagemodel',
            name='language_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=50, null=True),
        ),
    ]
